// ---- bars et lieux de sortie en soirée, toujours ouverts (pas datés) ----
const CURATED_BARS = [
  { id: "bar-nantes-1", isPlace: true, scene: "bar", city: "nantes", category: "Bar", title: "Bagadou", date: null, time: "", place: "11 rue Jean-Jacques Rousseau, Nantes", lat: 47.2160, lng: -1.5560, price: "Selon consommations", thumb: "", description: "Référence historique de la nuit nantaise, bar à cocktails au cœur du quartier Graslin." },
  { id: "bar-nantes-2", isPlace: true, scene: "bar", city: "nantes", category: "Bar", title: "Les 3 Corbeaux", date: null, time: "", place: "Quartier Bouffay, Nantes", lat: 47.2140, lng: -1.5530, price: "Selon consommations", thumb: "", description: "Taverne hors du temps au cœur du Bouffay, ambiance décalée et cocktails créatifs." },
  { id: "bar-nantes-3", isPlace: true, scene: "bar", city: "nantes", category: "Bar", title: "Levrette Café", date: null, time: "", place: "Nantes", lat: 47.2145, lng: -1.5545, price: "Selon consommations", thumb: "", description: "Rooftop avec DJ le week-end, terrasse dès l'après-midi le dimanche, privatisable pour les groupes." },
  { id: "bar-nantes-4", isPlace: true, scene: "bar", city: "nantes", category: "Bar", title: "OHM Town", date: null, time: "", place: "Bas-Chantenay, Nantes", lat: 47.2050, lng: -1.5850, price: "Selon consommations", thumb: "", description: "Bar, scène de musique vivante et biergarten dans un format unique à Nantes, quartier Bas-Chantenay." },
  { id: "bar-nantes-5", isPlace: true, scene: "bar", city: "nantes", category: "Bar", title: "Les Berthom", date: null, time: "", place: "Nantes", lat: 47.2130, lng: -1.5570, price: "Selon consommations", thumb: "", description: "Happy hour tous les jours de 17h à 20h, une des plages les plus larges de la ville. Idéal afterwork." },
  { id: "bar-nantes-6", isPlace: true, scene: "bar", city: "nantes", category: "Bar", title: "La Scierie", date: null, time: "", place: "Nantes", lat: 47.2100, lng: -1.5600, price: "Selon consommations", thumb: "", description: "Ouvert tous les jours dès 17h, ambiance festive avec DJ, idéal pour les groupes." },
  { id: "bar-nantes-7", isPlace: true, scene: "bar", city: "nantes", category: "Bar", title: "Big City Nantes", date: null, time: "", place: "Nantes", lat: 47.2090, lng: -1.5610, price: "Selon consommations", thumb: "", description: "Plus de 90 bières, cocktails et spiritueux, vue sur la Loire, parfait pour un apéro au soleil." },
  { id: "bar-nantes-8", isPlace: true, scene: "bar", city: "nantes", category: "Bar", title: "Licorne Noire", date: null, time: "", place: "Nantes", lat: 47.2150, lng: -1.5540, price: "Selon consommations", thumb: "", description: "Bar à cocktails élaborés dans une ambiance intimiste et soignée." },
  { id: "bar-nantes-9", isPlace: true, scene: "bar", city: "nantes", category: "Bar", title: "13'Or", date: null, time: "", place: "Rue des Carmélites, Nantes", lat: 47.2115, lng: -1.5545, price: "Selon consommations", thumb: "", description: "Nouvelle adresse du quartier très vivant de la rue des Carmélites." },
  { id: "bar-nantes-10", isPlace: true, scene: "bar", city: "nantes", category: "Bar", title: "Prohibition", date: null, time: "", place: "Quartier Bouffay, Nantes", lat: 47.2135, lng: -1.5525, price: "Selon consommations", thumb: "", description: "Plonge dans l'ambiance speakeasy des bars clandestins new-yorkais de la Prohibition." },
  { id: "bar-nantes-11", isPlace: true, scene: "bar", city: "nantes", category: "Bar", title: "Le Rabelais", date: null, time: "", place: "Nantes", lat: 47.2120, lng: -1.5555, price: "Selon consommations", thumb: "", description: "LE bar à bières et sport de Nantes : 4 écrans géants, 100 bières dont 27 pressions." },
  { id: "bar-nantes-12", isPlace: true, scene: "bar", city: "nantes", category: "Bar", title: "Au Bureau", date: null, time: "", place: "10 quai François-Mitterrand, Nantes", lat: 47.2103, lng: -1.5551, price: "Selon consommations", thumb: "", description: "Grands écrans pour tous les sports, ambiance conviviale au bord de la Loire." },
  { id: "bar-nantes-13", isPlace: true, scene: "bar", city: "nantes", category: "Bar", title: "Côté Plage (le Cotep)", date: null, time: "", place: "14 quai Turenne, Nantes", lat: 47.2095, lng: -1.5610, price: "Selon consommations", thumb: "", description: "Terrasse bien exposée et déco en bois, un classique nantais surnommé « le Cotep » par les habitués." },
  { id: "bar-nantes-14", isPlace: true, scene: "bar", city: "nantes", category: "Bar", title: "Obock", date: null, time: "", place: "Nantes", lat: 47.2080, lng: -1.5480, price: "Selon consommations", thumb: "", description: "Bar-restaurant animé : retransmissions sportives, soirées rock, blind-tests et DJ selon les soirs." },
  { id: "bar-nantes-15", isPlace: true, scene: "bar", city: "nantes", category: "Bar", title: "Gigg's Irish Pub", date: null, time: "", place: "Nantes", lat: 47.2160, lng: -1.5500, price: "Selon consommations", thumb: "", description: "Pub irlandais chaleureux, cuisine française, grande terrasse, ambiance familiale et conviviale." },
  { id: "bar-nantes-16", isPlace: true, scene: "bar", city: "nantes", category: "Bar", title: "Naoned", date: null, time: "", place: "Nantes", lat: 47.2145, lng: -1.5560, price: "Selon consommations", thumb: "", description: "Bar-restaurant proposant salades, fromages et planches, ambiance conviviale pour les retrouvailles." },
  { id: "bar-nantes-17", isPlace: true, scene: "bar", city: "nantes", category: "Bar", title: "Le Bateau Lavoir", date: null, time: "", place: "Nantes", lat: 47.2070, lng: -1.5590, price: "Selon consommations", thumb: "", description: "Bar-restaurant chaleureux, une valeur sûre pour un verre ou un repas simple entre amis." },
  { id: "bar-nantes-18", isPlace: true, scene: "bar", city: "nantes", category: "Bar", title: "Quartier du Hangar à Bananes", date: null, time: "", place: "Île de Nantes, Nantes", lat: 47.2070, lng: -1.5580, price: "Selon consommations", thumb: "", photo: "https://commons.wikimedia.org/wiki/Special:FilePath/Hangar_bananes_1.JPG", description: "Le quartier festif incontournable en bord de Loire : plusieurs bars et terrasses concentrés au même endroit, animé toute l'année." },
];

const __allEventsBaseBars = allEvents;
allEvents = function () {
  return [...__allEventsBaseBars(), ...CURATED_BARS];
};
