// ---- musées et lieux "à voir" pour des villes encore non couvertes (lot 2) ----
// (Amiens, Besançon, Clermont-Ferrand, Perpignan, Poitiers, Annecy, Colmar, La Rochelle)
const CURATED_MUSEUMS_3 = [
  // ---- Amiens ----
  { id: "musee3-amiens-1", isPlace: true, scene: "expo", city: "amiens", category: "À voir", title: "Musée de Picardie", date: null, time: "", place: "48 Rue de la République, Amiens", lat: 49.8934, lng: 2.3020, price: "Payant", thumb: "", description: "Beaux-Arts et archéologie dans un splendide palais du Second Empire, l'un des plus anciens musées de France." },
  { id: "musee3-amiens-2", isPlace: true, scene: "expo", city: "amiens", category: "À voir", title: "Cathédrale Notre-Dame d'Amiens", date: null, time: "", place: "Place Notre-Dame, Amiens", lat: 49.8944, lng: 2.3016, price: "Gratuit", thumb: "", description: "Plus vaste cathédrale gothique de France, classée à l'Unesco, avec son spectacle de lumières projeté en soirée sur la façade." },
  // ---- Besançon ----
  { id: "musee3-besancon-1", isPlace: true, scene: "expo", city: "besancon", category: "À voir", title: "Musée des Beaux-Arts et d'Archéologie", date: null, time: "", place: "1 Place de la Révolution, Besançon", lat: 47.2350, lng: 6.0250, price: "Payant", thumb: "", description: "Le plus ancien musée public de France, ouvert dès 1694, avec une belle collection de peinture ancienne et moderne." },
  { id: "musee3-besancon-2", isPlace: true, scene: "expo", city: "besancon", category: "À voir", title: "Citadelle de Besançon", date: null, time: "", place: "99 Rue des Fusillés de la Résistance, Besançon", lat: 47.2280, lng: 6.0300, price: "Payant", thumb: "", description: "Forteresse Vauban classée à l'Unesco dominant la ville, avec musées, espaces animaliers et panorama sur la boucle du Doubs." },
  // ---- Clermont-Ferrand ----
  { id: "musee3-clermont-1", isPlace: true, scene: "expo", city: "clermont", category: "À voir", title: "Cathédrale Notre-Dame-de-l'Assomption", date: null, time: "", place: "Place de la Victoire, Clermont-Ferrand", lat: 45.7772, lng: 3.0870, price: "Gratuit", thumb: "", description: "Cathédrale gothique construite en pierre de lave noire de Volvic, unique en son genre, cœur historique de Clermont-Ferrand." },
  { id: "musee3-clermont-2", isPlace: true, scene: "expo", city: "clermont", category: "À voir", title: "Musée d'Art Roger-Quilliot (MARQ)", date: null, time: "", place: "Place Louis Deteix, Clermont-Ferrand", lat: 45.7795, lng: 3.0930, price: "Gratuit", thumb: "", description: "Beaux-Arts du Moyen Âge au XXe siècle dans un ancien couvent, l'une des collections majeures d'Auvergne." },
  // ---- Perpignan ----
  { id: "musee3-perpignan-1", isPlace: true, scene: "expo", city: "perpignan", category: "À voir", title: "Palais des Rois de Majorque", date: null, time: "", place: "2 Rue des Archers, Perpignan", lat: 42.6941, lng: 2.8925, price: "Payant", thumb: "", description: "Forteresse royale du XIIIe siècle dominant la ville, cour d'honneur, chapelles superposées et vue sur les Pyrénées." },
  { id: "musee3-perpignan-2", isPlace: true, scene: "expo", city: "perpignan", category: "À voir", title: "Le Castillet", date: null, time: "", place: "Place de Verdun, Perpignan", lat: 42.6975, lng: 2.8955, price: "Payant", thumb: "", description: "Ancienne porte fortifiée en brique rose, symbole de Perpignan, abritant la Casa Pairal et ses collections catalanes." },
  // ---- Poitiers ----
  { id: "musee3-poitiers-1", isPlace: true, scene: "expo", city: "poitiers", category: "À voir", title: "Baptistère Saint-Jean", date: null, time: "", place: "Rue Jean Jaurès, Poitiers", lat: 46.5820, lng: 0.3390, price: "Payant", thumb: "", description: "L'un des plus anciens édifices chrétiens de France, fondé au IVe siècle, avec ses fresques romanes et ses cuves baptismales." },
  { id: "musee3-poitiers-2", isPlace: true, scene: "expo", city: "poitiers", category: "À voir", title: "Musée Sainte-Croix", date: null, time: "", place: "3bis Rue Jean Jaurès, Poitiers", lat: 46.5800, lng: 0.3400, price: "Payant", thumb: "", description: "Archéologie, Beaux-Arts et sculpture gallo-romaine dans un musée moderne au cœur du centre historique de Poitiers." },
  // ---- Annecy ----
  { id: "musee3-annecy-1", isPlace: true, scene: "expo", city: "annecy", category: "À voir", title: "Château d'Annecy", date: null, time: "", place: "Place du Château, Annecy", lat: 45.8988, lng: 6.1268, price: "Payant", thumb: "", description: "Ancienne résidence des comtes de Genève dominant la vieille ville, musée d'histoire locale et vues sur le lac." },
  { id: "musee3-annecy-2", isPlace: true, scene: "expo", city: "annecy", category: "À voir", title: "Palais de l'Isle", date: null, time: "", place: "3 Passage de l'Isle, Annecy", lat: 45.9005, lng: 6.1265, price: "Payant", thumb: "", description: "Ancienne prison sur un îlot au milieu du canal du Thiou, l'un des monuments les plus photographiés de France." },
  // ---- Colmar ----
  { id: "musee3-colmar-1", isPlace: true, scene: "expo", city: "colmar", category: "À voir", title: "Musée Unterlinden", date: null, time: "", place: "1 Rue des Unterlinden, Colmar", lat: 48.0776, lng: 7.3573, price: "Payant", thumb: "", description: "Ancien couvent dominicain abritant le célèbre retable d'Issenheim de Grünewald, l'un des chefs-d'œuvre de l'art européen." },
  { id: "musee3-colmar-2", isPlace: true, scene: "expo", city: "colmar", category: "À voir", title: "Musée Bartholdi", date: null, time: "", place: "30 Rue des Marchands, Colmar", lat: 48.0775, lng: 7.3585, price: "Payant", thumb: "", description: "Maison natale du sculpteur de la statue de la Liberté, maquettes et œuvres originales d'Auguste Bartholdi." },
  // ---- La Rochelle ----
  { id: "musee3-larochelle-1", isPlace: true, scene: "expo", city: "larochelle", category: "À voir", title: "Tours de La Rochelle", date: null, time: "", place: "Quai du Gabut, La Rochelle", lat: 46.1553, lng: -1.1520, price: "Payant", thumb: "", description: "Tour Saint-Nicolas et Tour de la Chaîne encadrant le Vieux-Port, symboles historiques de La Rochelle depuis le Moyen Âge." },
  { id: "musee3-larochelle-2", isPlace: true, scene: "expo", city: "larochelle", category: "À voir", title: "Aquarium La Rochelle", date: null, time: "", place: "Bassin des Grands Yachts, La Rochelle", lat: 46.1533, lng: -1.1548, price: "Payant", thumb: "", description: "L'un des plus grands aquariums privés d'Europe, requins, méduses et faune atlantique au bord du port des yachts." },
];

const __allEventsBaseMuseums3 = allEvents;
allEvents = function () {
  return [...__allEventsBaseMuseums3(), ...CURATED_MUSEUMS_3];
};
