// ---- musées et lieux "à voir" pour des villes encore non couvertes (lot 3) ----
// (Orléans, Valence, Chartres, Quimper, Arras, Tarbes, Montauban, Châlons-en-Champagne)
const CURATED_MUSEUMS_4 = [
  // ---- Orléans ----
  { id: "musee4-orleans-1", isPlace: true, scene: "expo", city: "orleans", category: "À voir", title: "Cathédrale Sainte-Croix d'Orléans", date: null, time: "", place: "Place Sainte-Croix, Orléans", lat: 47.9047, lng: 1.9105, price: "Gratuit", thumb: "", description: "Grande cathédrale gothique liée à l'histoire de Jeanne d'Arc, reconstruite après les guerres de Religion, au cœur d'Orléans." },
  { id: "musee4-orleans-2", isPlace: true, scene: "expo", city: "orleans", category: "À voir", title: "Musée des Beaux-Arts d'Orléans", date: null, time: "", place: "1 Rue Fernand Rabier, Orléans", lat: 47.9020, lng: 1.9060, price: "Payant", thumb: "", description: "L'une des plus riches collections de province, peinture du XVe au XXe siècle, juste derrière la cathédrale." },
  // ---- Valence ----
  { id: "musee4-valence-1", isPlace: true, scene: "expo", city: "valence", category: "À voir", title: "Cathédrale Saint-Apollinaire de Valence", date: null, time: "", place: "Place des Ormeaux, Valence", lat: 44.9310, lng: 4.8907, price: "Gratuit", thumb: "", description: "Cathédrale romane classée, où fut sacré le pape Pie VI, dominant la vieille ville de Valence." },
  { id: "musee4-valence-2", isPlace: true, scene: "expo", city: "valence", category: "À voir", title: "Musée de Valence, art et archéologie", date: null, time: "", place: "4 Place des Ormeaux, Valence", lat: 44.9315, lng: 4.8910, price: "Payant", thumb: "", description: "Dessins d'Hubert Robert, archéologie et vue sur la vallée du Rhône, installé dans l'ancien palais épiscopal." },
  // ---- Chartres ----
  { id: "musee4-chartres-1", isPlace: true, scene: "expo", city: "chartres", category: "À voir", title: "Cathédrale Notre-Dame de Chartres", date: null, time: "", place: "16 Cloître Notre-Dame, Chartres", lat: 48.4472, lng: 1.4885, price: "Gratuit", thumb: "", description: "Chef-d'œuvre gothique classé à l'Unesco, célèbre pour ses vitraux du XIIIe siècle et son labyrinthe au sol." },
  { id: "musee4-chartres-2", isPlace: true, scene: "expo", city: "chartres", category: "À voir", title: "Musée des Beaux-Arts de Chartres", date: null, time: "", place: "29 Cloître Notre-Dame, Chartres", lat: 48.4475, lng: 1.4890, price: "Payant", thumb: "", description: "Ancien palais épiscopal juste à côté de la cathédrale, peinture, émaux et clavecins historiques." },
  // ---- Quimper ----
  { id: "musee4-quimper-1", isPlace: true, scene: "expo", city: "quimper", category: "À voir", title: "Cathédrale Saint-Corentin de Quimper", date: null, time: "", place: "Place Saint-Corentin, Quimper", lat: 47.9958, lng: -4.1013, price: "Gratuit", thumb: "", description: "Cathédrale gothique aux flèches élancées, cœur historique de la capitale de la Cornouaille." },
  { id: "musee4-quimper-2", isPlace: true, scene: "expo", city: "quimper", category: "À voir", title: "Musée des Beaux-Arts de Quimper", date: null, time: "", place: "40 Place Saint-Corentin, Quimper", lat: 47.9960, lng: -4.1010, price: "Payant", thumb: "", description: "Belle collection de peinture bretonne et européenne, face à la cathédrale, dans un cadre Belle Époque." },
  // ---- Arras ----
  { id: "musee4-arras-1", isPlace: true, scene: "expo", city: "arras", category: "À voir", title: "Beffroi et Hôtel de ville d'Arras", date: null, time: "", place: "Place des Héros, Arras", lat: 50.2921, lng: 2.7817, price: "Payant", thumb: "", description: "Beffroi gothique classé à l'Unesco dominant les magnifiques places baroques flamandes d'Arras, montée jusqu'au panorama." },
  { id: "musee4-arras-2", isPlace: true, scene: "expo", city: "arras", category: "À voir", title: "Musée des Beaux-Arts d'Arras", date: null, time: "", place: "22 Rue Paul Doumer, Arras", lat: 50.2890, lng: 2.7825, price: "Payant", thumb: "", description: "Installé dans l'ancienne abbaye Saint-Vaast, peinture, sculpture et tapisseries d'Arras à travers les siècles." },
  // ---- Tarbes ----
  { id: "musee4-tarbes-1", isPlace: true, scene: "expo", city: "tarbes", category: "À voir", title: "Musée Massey", date: null, time: "", place: "Jardin Massey, Tarbes", lat: 43.2313, lng: 0.0755, price: "Payant", thumb: "", description: "Musée international des Hussards et Beaux-Arts, installé dans un cloître gothique remonté au cœur du jardin Massey." },
  { id: "musee4-tarbes-2", isPlace: true, scene: "expo", city: "tarbes", category: "À voir", title: "Haras National de Tarbes", date: null, time: "", place: "Avenue Alsace-Lorraine, Tarbes", lat: 43.2280, lng: 0.0720, price: "Payant", thumb: "", description: "Haras historique fondé par Napoléon, berceau du cheval tarbais, écuries du XIXe siècle ouvertes à la visite." },
  // ---- Montauban ----
  { id: "musee4-montauban-1", isPlace: true, scene: "expo", city: "montauban", category: "À voir", title: "Musée Ingres Bourdelle", date: null, time: "", place: "19 Rue de l'Hôtel de Ville, Montauban", lat: 44.0175, lng: 1.3555, price: "Payant", thumb: "", description: "Dans l'ancien palais épiscopal au bord du Tarn, œuvres du peintre Ingres et du sculpteur Bourdelle, natifs de la ville." },
  { id: "musee4-montauban-2", isPlace: true, scene: "expo", city: "montauban", category: "À voir", title: "Place Nationale de Montauban", date: null, time: "", place: "Place Nationale, Montauban", lat: 44.0178, lng: 1.3545, price: "Gratuit", thumb: "", description: "Grande place à arcades de brique rose du XVIIe siècle, emblème architectural du centre historique de Montauban." },
  // ---- Châlons-en-Champagne ----
  { id: "musee4-chalons-1", isPlace: true, scene: "expo", city: "chalons", category: "À voir", title: "Musée des Beaux-Arts et d'Archéologie de Châlons", date: null, time: "", place: "Place Godart, Châlons-en-Champagne", lat: 48.9563, lng: 4.3650, price: "Gratuit", thumb: "", description: "Peinture, archéologie régionale et arts décoratifs, au cœur du centre historique de Châlons-en-Champagne." },
  { id: "musee4-chalons-2", isPlace: true, scene: "expo", city: "chalons", category: "À voir", title: "Cathédrale Saint-Étienne de Châlons", date: null, time: "", place: "Place de la République, Châlons-en-Champagne", lat: 48.9540, lng: 4.3660, price: "Gratuit", thumb: "", description: "Cathédrale gothique aux beaux vitraux du XIIIe au XVIe siècle, l'un des monuments majeurs de Champagne." },
];

const __allEventsBaseMuseums4 = allEvents;
allEvents = function () {
  return [...__allEventsBaseMuseums4(), ...CURATED_MUSEUMS_4];
};
