// ---- musées et lieux "à voir" pour des villes encore non couvertes (lot 9, dernier lot continental) ----
// (Alençon, Bar-le-Duc, Bourg-en-Bresse, Chaumont, Digne-les-Bains, Moulins, Privas, Saint-Lô, La Roche-sur-Yon)
const CURATED_MUSEUMS_10 = [
  // ---- Alençon ----
  { id: "musee10-alencon-1", isPlace: true, scene: "expo", city: "alencon", category: "À voir", title: "Musée des Beaux-Arts et de la Dentelle", date: null, time: "", place: "Cour Carrée de la Dentelle, Alençon", lat: 48.4325, lng: 0.0930, price: "Gratuit", thumb: "", description: "Dédié au point d'Alençon, dentelle à l'aiguille classée à l'Unesco, et peinture des XVIIe-XIXe siècles." },
  { id: "musee10-alencon-2", isPlace: true, scene: "expo", city: "alencon", category: "À voir", title: "Basilique Notre-Dame d'Alençon", date: null, time: "", place: "Rue de Lattre de Tassigny, Alençon", lat: 48.4315, lng: 0.0920, price: "Gratuit", thumb: "", description: "Basilique flamboyante réputée pour son porche gothique sculpté et ses vitraux Renaissance, cœur de la ville." },
  // ---- Bar-le-Duc ----
  { id: "musee10-barleduc-1", isPlace: true, scene: "expo", city: "barleduc", category: "À voir", title: "Église Saint-Étienne de Bar-le-Duc", date: null, time: "", place: "Rue Saint-Pierre, Bar-le-Duc", lat: 48.7690, lng: 5.1590, price: "Gratuit", thumb: "", description: "Abrite le célèbre 'Transi', sculpture funéraire de René de Chalon par Ligier Richier, chef-d'œuvre de la Renaissance." },
  { id: "musee10-barleduc-2", isPlace: true, scene: "expo", city: "barleduc", category: "À voir", title: "Musée Barrois", date: null, time: "", place: "Rue François de Guise, Bar-le-Duc", lat: 48.7705, lng: 5.1595, price: "Gratuit", thumb: "", description: "Archéologie, sculpture et histoire du Barrois, installé dans l'ancien château des ducs de Bar, en ville haute." },
  // ---- Bourg-en-Bresse ----
  { id: "musee10-bourgenbresse-1", isPlace: true, scene: "expo", city: "bourgenbresse", category: "À voir", title: "Monastère royal de Brou", date: null, time: "", place: "63 Boulevard de Brou, Bourg-en-Bresse", lat: 46.1990, lng: 5.2340, price: "Payant", thumb: "", description: "Joyau du gothique flamboyant, église et cloîtres Renaissance édifiés par Marguerite d'Autriche, l'un des plus beaux monuments de France." },
  { id: "musee10-bourgenbresse-2", isPlace: true, scene: "expo", city: "bourgenbresse", category: "À voir", title: "Musée du Monastère de Brou", date: null, time: "", place: "63 Boulevard de Brou, Bourg-en-Bresse", lat: 46.1992, lng: 5.2342, price: "Payant", thumb: "", description: "Peinture et art sacré dans les anciens bâtiments conventuels du monastère de Brou." },
  // ---- Chaumont ----
  { id: "musee10-chaumont-1", isPlace: true, scene: "expo", city: "chaumont", category: "À voir", title: "Basilique Saint-Jean-Baptiste de Chaumont", date: null, time: "", place: "Place Saint-Jean, Chaumont", lat: 48.1120, lng: 5.1400, price: "Gratuit", thumb: "", description: "Basilique gothique à l'escalier Renaissance remarquable, principal édifice religieux du centre historique de Chaumont." },
  { id: "musee10-chaumont-2", isPlace: true, scene: "expo", city: "chaumont", category: "À voir", title: "Musée d'Art et d'Histoire de Chaumont", date: null, time: "", place: "Rue du Vieux Château, Chaumont", lat: 48.1130, lng: 5.1395, price: "Gratuit", thumb: "", description: "Collections locales et archéologie, installées près du donjon, vestige du château des comtes de Champagne." },
  // ---- Digne-les-Bains ----
  { id: "musee10-digne-1", isPlace: true, scene: "expo", city: "digne", category: "À voir", title: "Musée Gassendi", date: null, time: "", place: "64 Boulevard Gassendi, Digne-les-Bains", lat: 44.0930, lng: 6.2340, price: "Payant", thumb: "", description: "Rencontre entre art contemporain et sciences de la Terre, dans un bel hôtel-Dieu du XVIIe siècle." },
  { id: "musee10-digne-2", isPlace: true, scene: "expo", city: "digne", category: "À voir", title: "Cathédrale Saint-Jérôme de Digne", date: null, time: "", place: "Boulevard Gassendi, Digne-les-Bains", lat: 44.0920, lng: 6.2360, price: "Gratuit", thumb: "", description: "Cathédrale gothique du XVIe siècle, principal édifice religieux du centre-ville de Digne-les-Bains." },
  // ---- Moulins ----
  { id: "musee10-moulins-1", isPlace: true, scene: "expo", city: "moulins", category: "À voir", title: "Cathédrale Notre-Dame de Moulins", date: null, time: "", place: "Rue de l'Horloge, Moulins", lat: 46.5655, lng: 3.3335, price: "Gratuit", thumb: "", description: "Abrite le célèbre Triptyque du Maître de Moulins, chef-d'œuvre de la peinture française de la fin du XVe siècle." },
  { id: "musee10-moulins-2", isPlace: true, scene: "expo", city: "moulins", category: "À voir", title: "Centre National du Costume de Scène", date: null, time: "", place: "Route de Montilly, Moulins", lat: 46.5605, lng: 3.3220, price: "Payant", thumb: "", description: "Costumes de spectacle de l'Opéra de Paris et de grandes compagnies, dans une ancienne caserne du Quartier Villars." },
  // ---- Privas ----
  { id: "musee10-privas-1", isPlace: true, scene: "expo", city: "privas", category: "À voir", title: "Vieux Pont de Privas", date: null, time: "", place: "Pont Louis XIII, Privas", lat: 44.7345, lng: 4.5975, price: "Gratuit", thumb: "", description: "Pont historique enjambant l'Ouvèze, vestige emblématique du siège de la ville au XVIIe siècle." },
  { id: "musee10-privas-2", isPlace: true, scene: "expo", city: "privas", category: "À voir", title: "Ruines du Château de Privas", date: null, time: "", place: "Colline du Château, Privas", lat: 44.7365, lng: 4.5995, price: "Gratuit", thumb: "", description: "Vestiges du château détruit par Richelieu, offrant un point de vue dégagé sur la préfecture ardéchoise." },
  // ---- Saint-Lô ----
  { id: "musee10-stlo-1", isPlace: true, scene: "expo", city: "stlo", category: "À voir", title: "Haras National de Saint-Lô", date: null, time: "", place: "Avenue du Maréchal Juin, Saint-Lô", lat: 49.1160, lng: -1.0870, price: "Payant", thumb: "", description: "Haras historique fondé par Napoléon Ier, reconstruit après-guerre, berceau du cheval de sport Selle Français." },
  { id: "musee10-stlo-2", isPlace: true, scene: "expo", city: "stlo", category: "À voir", title: "Musée des Beaux-Arts de Saint-Lô", date: null, time: "", place: "Place du Champ de Mars, Saint-Lô", lat: 49.1150, lng: -1.0915, price: "Gratuit", thumb: "", description: "Tapisseries et peinture normande, dans une ville largement reconstruite après les bombardements de 1944." },
  // ---- La Roche-sur-Yon ----
  { id: "musee10-laroche-1", isPlace: true, scene: "expo", city: "laroche", category: "À voir", title: "Haras de la Vendée", date: null, time: "", place: "2 Rue du Haras, La Roche-sur-Yon", lat: 46.6740, lng: -1.4270, price: "Payant", thumb: "", description: "Ancien haras national du XIXe siècle, aujourd'hui centre équestre et culturel dédié au cheval en Vendée." },
  { id: "musee10-laroche-2", isPlace: true, scene: "expo", city: "laroche", category: "À voir", title: "Place Napoléon", date: null, time: "", place: "Place Napoléon, La Roche-sur-Yon", lat: 46.6700, lng: -1.4260, price: "Gratuit", thumb: "", description: "Immense place centrale voulue par Napoléon Ier, statue équestre de l'Empereur, cœur de la ville nouvelle qu'il a fait bâtir." },
];

const __allEventsBaseMuseums10 = allEvents;
allEvents = function () {
  return [...__allEventsBaseMuseums10(), ...CURATED_MUSEUMS_10];
};
